import { test, expect } from '@playwright/test'

// registrarse

//

test('crearYUnirseGrupo', async ({ page }) => {
  await page.goto('http://localhost:3000/')
  await page.getByLabel('Email address').click()
  await page.getByLabel('Email address').fill('raulat99@gmail.com')
  await page.getByLabel('Email address').press('Tab')
  await page.getByLabel('Password').click()
  await page.getByLabel('Password').fill('asdf')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await page.locator('#createGroup').click()
  await page.getByPlaceholder('Introduce el nombre').fill('Primer grupo')
  await page.getByPlaceholder('Introduce el código').click()
  await page.getByPlaceholder('Introduce el código').fill('inv1')
  await page.getByPlaceholder('Introduce la url').click()
  await page.getByPlaceholder('Introduce la url').fill('')
  await page.getByPlaceholder('Introduce la url').click()
  await page.getByPlaceholder('Introduce la url').fill('https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Flogos-world.net%2Fwp-content%2Fuploads%2F2020%2F12%2FUCLM-Symbol.png&f=1&nofb=1&ipt=b99da344ca27ce1b51d90d6adb3fcda700ab6b958336c65e0492cbe7f864232a&ipo=images')
  await page.getByRole('button', { name: 'Crear' }).click()
  await page.locator('#input').click()
  await page.locator('#input').fill('Hola!')
  await page.locator('#input').press('Enter')
  await page.locator('#input').fill('que tal grupo!!!')
  await page.locator('#input').press('Enter')
  await page.getByRole('link', { name: 'Salir' }).click()
  await page.getByLabel('Email address').click()
  await page.getByLabel('Email address').fill('raulat00@gmail.com')
  await page.getByLabel('Password').click()
  await page.getByLabel('Password').fill('asdf')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await page.locator('#createGroup').click()
  await page.getByPlaceholder('Introduce el nombre').click()
  await page.getByPlaceholder('Introduce el nombre').fill('Primer grupo')
  await page.getByPlaceholder('Introduce el código').click()
  await page.getByPlaceholder('Introduce el código').fill('inv1')
  await page.getByRole('button', { name: 'Unirse' }).click()
  await page.getByRole('button', { name: 'Primer grupo' }).click()
  await page.locator('#input').click()
  await page.locator('#input').fill('Bieeeen')
  await page.locator('#input').press('Enter')
  await page.locator('#input').fill('y vosotros??')
  await page.locator('#input').press('Enter')
  await page.locator('#input').fill('jajajajja')
  await page.locator('#input').press('Enter')
  await page.getByRole('link', { name: 'Salir' }).click()
  await page.close()
})
